### ISSUE TITLE
Card Numbering

### ISSUE THREAD

**Issue by jorshthehacker** [raohmaru/generic-mse2-template#1]
There's an issue with the card numbering script. It displays as a negative number.

**Comment by raohmaru** [comment]
The card numbering is composed of "[set code] - [set language][card number]". If it displays a negative number then it is because your set is missing the set code (you can define one in Set Info > Code).

**Comment by raohmaru** [comment]
Additonally to your comment, I have added a new feature to the template: customization of the card numbering. Please read the [readme](https://github.com/raohmaru/generic-mse2-template/blob/master/README.md) for more information and download the latest version [here](https://github.com/raohmaru/generic-mse2-template/releases).
